name: pharmacy_analysis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - matplotlib.pyplot
  - shapely
  - pathlib
  - altair
  - streamlit
  - matplotlib.patches
  - matplotlib.lines
